### PR TITLE
Add GH Action Spell Check

### PR DESCRIPTION
**Pull request by WSLUser**
This is a test pull request. Please do not merge until it successfully shows in build steps.

### CODE REVIEW

**Comment by WSLUser** [comment]
@crramirez This actually needs to be on master for changes to test out successfully. Unlike other pull requests, GH actions aren't included in the build so adding to master won't make any changes to the releases.

**Comment by WSLUser** [comment]
So I'm starting to think GH Actions don't work so well with Circle CI/Travis CI. Only repos I've seen it successfully working don't use either of those.

**Comment by crramirez** [comment]
But what are you trying to do? I barely understand what you did.

**Comment by WSLUser** [comment]
Its a spell checker running as a GH Action. Any misspellings found in code will be correctly identified and you can add exceptions when needed. Windows Terminal uses it. But looks like it would need to be added as a build step in Circle CI, which I'm not sure how to do and don't think is supported as there's no documentation for using it in CI outside of GH Action.

**Pull request closed without merging**
