### PR TITLE
Development Pull

### PR DESCRIPTION
**Pull request by sirredbeard**

### CODE REVIEW

**Comment by sirredbeard** [comment]
I am going to test this over the coming week and expect to move into master a few days after that.

**Comment by grufwub** [comment]
given the nature of the uninstall scripts these could do with confirming that there's no adverse effects from as many of us possible ideally. i've tested them countless times myself, but outside of that extra sets of eyes + testing environments are always a good idea!

**Comment by patrick330602** [comment]
My tests for Start Menu Shortcut Creator encountered a problem... it stopped early, I tried to figure out what happened but cannot
image

**Comment by crramirez** [comment]
> My tests for Start Menu Shortcut Creator encountered a problem... it stopped early, I tried to figure out what happened but cannot
> image
> 
> UPDATE: I think this is the bash problem of WSL 2... I also encounter bash problem with `wslfetch`

Ok I double checked and it works in WSL 1 with Windows 1809

**Comment by sirredbeard** [comment]
Did some testing this past weekend, didn't notice anything odd.

I am comfortable moving this into master this week.

Any last minute holds?

**Pull request merged**
