### PR TITLE
Add uninstall scripts

### PR DESCRIPTION
**Pull request by grufwub**
Add a set of uninstall scripts users can access to remove components installed by pengwin-setup that aren't managed by other package managers (e.g. APT).

### CODE REVIEW

**Comment by sirredbeard** [comment]
Wow, a lot of work going in here. I like it!

**Comment by grufwub** [comment]
> Wow, a lot of work going in here. I like it!

thank you! it's been quite a good exercise in checking over current install scripts too, especially with the more cloudcli focused ones where I may have tested them in the past, but didn't have too much of an idea of their inner workings (install locations etc). have also come up with a number of other possible install script improvements i'm jotting down on a todo list for later, just simple changes to make our lives easier with development in the future.

i'm getting towards a state where i might be able to begin testing them all, haven't got too many more to write! though I've separated them all out into different files, and some of the smaller scripts (like each of the cloudcli uninstallers) I might consolidate.

**Comment by grufwub** [comment]
Mostly finished now I think! Going to begin testing this on my main Windows install, then I'm sure there's no 'game-breaking' bugs I'll open it up for review so we can push to development and test it out.

**Comment by grufwub** [comment]
So nearly ready to open for review... Is mostly finished, just need to write an uninstall menu and add it to the pengwin-setup main menu!

**Comment by grufwub** [comment]
Now ready to review! Only thing I need to check on with this is in some cases I think autoremove is uninstalling Python2 if Python3 is installed. Which is fine, just with the way that Debian-based distributions handle this it means `python` does nothing and instead the user has to launch via `python3`. But this may just be an issue introduced with upcoming Buster as opposed to this script, I'll do some more testing, figure it out and add a list of protected packages under my remove_package function if so

**Pull request merged**
