### PR TITLE
Loginshell path fix

### PR DESCRIPTION
**Pull request by grufwub**
Update fix for PATH with explorer integration when user home has spaces (on Windows 10 1903+). This issue only shows up on my Windows install where my user home folder is 'kim (grufwub)', whereas the other install with 'kimja' has no issues. This is likely mitigating an upstream issue.

### CODE REVIEW

**Comment by grufwub** [comment]
Ah yes this is true. I'll find an alternative solution to looking for /mnt 👍

**Comment by grufwub** [comment]
Okay I think this new alternative should work out well, and fix the same (but differently presenting) issue on older 1809 installs. I'm just downloading a quick 1809 install to test it out

**Comment by sirredbeard** [comment]
Does this address your concern @crramirez?

**Comment by grufwub** [comment]
I did tests on an 1809 build and they didn't seem to be present so I'm not entirely sure what happened. Either way the remaining fix works on my current 1903 build, and doesn't rely on a specific mount point, it just looks for the AppData/Local/WindowsApps path and takes the mount point from the beginning of there.

**Pull request merged**
