### PR TITLE
Fix powershell dependencies

### PR DESCRIPTION
**Pull request by sirredbeard**

### CODE REVIEW

**Comment by crramirez** [comment]
We can use the same approach as we did with vscode and dotnet. Or if this is better we can change the code in vscode and dotnet

**Comment by sirredbeard** [comment]
Savings this for reference https://github.com/WhitewaterFoundry/pengwin-setup/blob/c03e64201b337bddf75529ba7bc8e994e0e6f7b2/pengwin-setup.d/dotnet.sh#L13

**Comment by crramirez** [comment]
Why the pinning is necessary in this case?

**Comment by sirredbeard** [comment]
Its probably not.

**Pull request merged**
